### ISSUE TITLE
Add POIs for road exits

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#160]
These are in highway:motorway_junction
and the ref stores the exit number.

**Comment by nvkelso** [comment]
cc @sensescape

**Comment by nvkelso** [comment]
These will need a special type of road shield, cc @bcamper and @meetar.

**Comment by zerebubuth** [comment]
With an appropriate icon and entry in the scene file:

```yaml
        exits:
          filter: { highway: motorway_junction }
          draw:
            icons:
              size: 21px
              sprite: wings-joint
              interactive: true
              visible: true
            text:
              visible: true
              interactive: true
              text_source: ref
              font:
                fill: *text_fill
                size: 12px
                stroke: { color: *text_stroke, width: 4 }
```

It looks like this:

![us_101_exit_433-after](https://cloud.githubusercontent.com/assets/271360/11637375/daac27d2-9d18-11e5-8fc2-976b6f455f5b.jpg)
