### ISSUE TITLE
OSM boundary funk (ways, relations)

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#180]
Reviewing this tile along the California and Oregon boundary it looks like we're returning relations (note the negative OSM ids) and ways.

http://vector.mapzen.com/osm/all/10/159/380.topojson?api_key=vector-tiles-HqUVidw

But the ways (mostly) don't have names! 

We should generate a "Left - Right" synthetic name for basic labeling, and an explicate name:left and name:right pair for advanced labeling on the ways, and stop exporting the relations. Bonus points for preserving the localized names.

**Comment by nvkelso** [comment]
Related: https://github.com/tangrams/tangram/pull/177

**Comment by zerebubuth** [comment]
After mapzen/TileStache#51 and #216, we have data like this. For example, just looking at the name attribute:

![boundaries_names_inline](https://cloud.githubusercontent.com/assets/271360/9909130/c48e8d3e-5c8e-11e5-9415-36f900798ad8.png)

Or, using the translations in the `left:name:*` and `right:name:*`:

![boundaries_left_right_translation](https://cloud.githubusercontent.com/assets/271360/9909152/d58b211a-5c8e-11e5-93fa-68cc2cab7cf0.png)

Using the following scene file fragment:

```yaml
    boundaries:
      data: { source: osm }
      draw:
        lines:
          order: 4
          color: '#808080'
          width: 2px
      admin_4:
	filter: { admin_level: '4' }
        draw:
          lines:
            width: 6px
          text:
            text_source: |
              function() {                                                                  
                return feature['left:name:el'] + "/" + feature['right:name:el']             
              }                                                                             
            font:
              fill: '#404040'
              typeface: 500 18px Helvetica
              stroke: { color: '#88bbee', width: 4 }
```
