### ISSUE TITLE
Add city wall lines

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#188]
Old cities have old walls, let's show them on the map:

Background reading:

https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dcity_wall

**Comment by nvkelso** [comment]
The `boundaries` layer seems to make the most sense for this.

**Comment by zerebubuth** [comment]
After #329, and with the following scene file snippet:

```yaml
        city_walls:
          filter: { kind: city_wall }
          draw:
            lines:
              interactive: true
              order: 8
              color: '#ff0000'
              width: 4px
```

Around [George's Island](https://www.openstreetmap.org/#map=18/44.64117/-63.55951), I get:

## Before

![georges_island_z18_before](https://cloud.githubusercontent.com/assets/271360/10703299/f86d8970-79c6-11e5-912f-2ef0ca6eb348.jpg)

## After

![georges_island_z18_after](https://cloud.githubusercontent.com/assets/271360/10703303/fe3d99bc-79c6-11e5-89df-664f234ea999.jpg)

There are some other features visible in the OSM carto map, which are tagged as `barrier=retaining_wall`. Let me know if you want them included too.
