### ISSUE TITLE
Add platforms to transit layer

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#244]
As referenced in https://github.com/mapzen/vector-datasource/issues/194:

BART platforms should really be marked `railway:platform` and be included in the `transit` layer.

See how to do it right in Moscow:
http://www.openstreetmap.org/#map=17/55.75196/37.60592

<img width="673" alt="screen shot 2015-09-24 at 22 26 20" src="https://cloud.githubusercontent.com/assets/853051/10093728/88e1c354-630b-11e5-9b90-2d7b6748b0bf.png">

**Comment by zerebubuth** [comment]
After #429, and with a wholly appropriately festive style:

```yaml
    platforms:
      data: { source: osm, layer: transit }
      filter: { kind: platform }
      draw:
        lines:
          color: '#ff0000'
          width: 5m
          order: 10
        polygons:
          color: '#ff0000'
          order: 10
```

## Glen Park station

Before:
![glen-park-z18-before](https://cloud.githubusercontent.com/assets/271360/11658665/ad4c1510-9dbb-11e5-851c-8c4148a46f82.jpg)

After:
![glen-park-z18-after](https://cloud.githubusercontent.com/assets/271360/11658672/b216a4b6-9dbb-11e5-97bc-15d82055c6c0.jpg)

(Drawing under the buildings seemed like the right thing to do here, and is the default anyway. But worth noting that the OSM map draws platforms, even underground ones, above buildings. Of course, this is under the control of the style, but I thought it was worth mentioning in case we look at a place where we're expecting to see platforms but they're rendered underneath a building.)

## Atlantic Center station

Before:
![atlantic-center-z18-before](https://cloud.githubusercontent.com/assets/271360/11658675/b6fcb696-9dbb-11e5-89b3-2cf4fa5bb090.jpg)

After:
![atlantic-center-z18-after](https://cloud.githubusercontent.com/assets/271360/11658678/ba9253ce-9dbb-11e5-9ac3-980aa97d933e.jpg)
