### ISSUE TITLE
Too many subway stations visible at zoom 13

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#268]
At zoom 13 there's a crazy number of subway stations covering the map in NYC and other saturated transit markets (lucky them).

We should thin those out, only including significant stations. Since we're already using OSM area (landuse, building area) as a proxy... this probably that means 2+ lines coming together, with more lines winning over less lines (3 lines wins over 2 lines at a transfer station).

**Comment by zerebubuth** [comment]
I've changed the scene file section for train stations to this, locally:

```yaml
                train-station:
                    filter: { kind: [station, train-staion] }
                    draw: { icons: { sprite: train-station } }
                    low-priority:
                      filter: { rank: { min: 9 } }
                      draw: { icons: { size: [[13, 8px], [15, 12px]] } }
```

Which means it's drawing a smaller icon for the higher ranked stations. This is the effect on NYC:

### Before, z13

![new_york_z13_before_2](https://cloud.githubusercontent.com/assets/271360/10640939/f46fea52-780e-11e5-9b31-9c7d7cce7b39.jpg)

### After, z13

![new_york_z13_after_2](https://cloud.githubusercontent.com/assets/271360/10640951/fff991a2-780e-11e5-95b1-2bb5fb188432.jpg)

### Before, z14

![new_york_z14_before_2](https://cloud.githubusercontent.com/assets/271360/10640961/08b04dcc-780f-11e5-8be1-de7249402246.jpg)

### After, z14

![new_york_z14_after_2](https://cloud.githubusercontent.com/assets/271360/10640971/0c4fbc42-780f-11e5-922e-ce9b228e9402.jpg)
