### ISSUE TITLE
Add piste routes to road layer

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#342]
We have paths, we're adding aerialway line features for the ski chair lifts and such, but we don't have the downhill, x-country & etc ski routes (e.g.: `route=piste`) that everyone goes to the mountain for in the first place. 

Core tags:

- [ ] piste:type > piste_type
- [ ] piste:difficulty > piste_difficulty
- [ ] piste:grooming > piste_grooming

Other tags that might be interesting:

- [ ] piste:name - sometimes the piste route name is different than the basic feature name?
- [ ] piste:abandoned - if it's abandoned, don't export it in tiles?
- [ ] ski=designated or ski=yes as appropriate if tagged on a path or other way not marked piste
- [ ] snowshoe=designated or showshoe=yes as appropriate if tagged on a path or other way not marked piste
- [ ] distance=number - official length of the complete route, useful for text labeling
- [ ] symbol=piste markings - textual description, useful for symbol labeling

We already include these types of tags on road layer features:

- [ ] name=* name of the piste (if it has one)
- [ ] ref=number reference code for the piste
- [ ] operator=* organisation that is responsible for the provision and maintenance of the route
- [ ] network=* name of the network of routes of which this one is part
- [ ] colour=* - colour normally associated with the route when presented on a map

See:

* http://wiki.openstreetmap.org/wiki/Piste_Maps
* http://wiki.openstreetmap.org/wiki/Proposed_features/Tag:route%3Dpiste
* http://wiki.openstreetmap.org/wiki/WikiProject_Piste_Maps
* http://wiki.openstreetmap.org/wiki/OpenPisteMap
* http://www.opensnowmap.org

**Comment by zerebubuth** [comment]
@nvkelso One thing I've found; we're not catching pistes which are not "interesting" in some other way - most appear to be highways (paths, usually) or have names, but some, such as [way 365603700](http://www.openstreetmap.org/way/365603700) don't. Currently we're missing them from the rendering database, and it would take some fiddling to include them. Can I assume it's okay to go ahead with the knowledge that we'll be missing some (about 35%) of these ways, or do we need to address that first?

**Comment by nvkelso** [comment]
@zerebubuth If it's ≤ day's work then add them in now, else make a new issue (and relate it to this one) and we'll tackle adding in those extra ones in a future release. Consider the total time to include ops time to deploy this to prod, not just dev the feature.

**Comment by zerebubuth** [comment]
Added pistes in the #422 and mapzen/TileStache#98. Now it looks like this in Lake Tahoe:

## Zoom 13

Before:
![lake-tahoe-z13-before](https://cloud.githubusercontent.com/assets/271360/11598149/1855459a-9ab8-11e5-907e-49afe6429bf1.jpg)

After:
![lake-tahoe-z13-after](https://cloud.githubusercontent.com/assets/271360/11598157/2481ac0a-9ab8-11e5-92f0-6a79af25ca33.jpg)

## Zoom 15:

Before:
![lake-tahoe-z15-before](https://cloud.githubusercontent.com/assets/271360/11598166/2c05fa3a-9ab8-11e5-8504-cb1083da6aec.jpg)

After:
![lake-tahoe-z15-after](https://cloud.githubusercontent.com/assets/271360/11598171/30265c72-9ab8-11e5-93c4-4596c69edec5.jpg)

With the following scene snippet:

```yaml
        piste:
            filter: { kind: piste }
            draw:
                lines:
                    order: 5
                    cap: round
                    join: round
                    color: '#909090'
                    width: [[13,3px],[15, 4px], [16, 5px], [18, 10m], [19, 15m]]
                text:
                  priority: 8
                  visible: true
                  text_source: name
                  font:
                    fill: *text_fill
                    size: 12px
                    stroke: { color: *text_stroke_park, width: 4 }
            easy:
              filter: { piste_difficulty: easy }
              draw: { lines: { color: '#ff0000' } }
            intermediate:
              filter: { piste_difficulty: intermediate }
              draw: { lines: { color: '#0000ff' } }
            expert:
              filter: { piste_difficulty: [expert, advanced] }
              draw: { lines: { color: '#000000' } }
```
