### ISSUE TITLE
At low and mid-zooms, merge "same" road segments

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#358]
We're sending over a lot of chunky data in tiles at low- and mid- zooms which results in larger file sizes, longer time to render, and makes drawing pretty labels difficult (lots of colliding labels on small segments instead of spaced labels over longer runs.

For example, zoom 8:

![screen shot 2015-10-29 at 5 43 05 pm](https://cloud.githubusercontent.com/assets/853051/10833035/485f245a-7e4c-11e5-85ae-d241775188f4.png)

```
roads:
    data: { source: osm }
    filter: { not: { kind: [rail, ferry] } }
    draw:
        lines:
            order: 2
            # color: '#777'
            color: Style.color.randomColor()
            width: 2px
```
Download full [scene.txt](https://github.com/mapzen/vector-datasource/files/23796/scene.txt) file (rename txt to yaml) »

/cc @bcamper, @sensescape, @zerebubuth, discuss!
