### ISSUE TITLE
Add beach to landuse AOIs

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#366]
Strips of sand are a summer's long lost love.

Baker Beach in SF, for instance:

/#15/37.7924/-122.4866
http://vector.mapzen.com/osm/all/15/5235/12663.topojson?api_key=vector-tiles-HqUVidw

**Comment by nvkelso** [comment]
There's probably something here for `surface` type?

**Comment by zerebubuth** [comment]
In the `landuse` layer, right?

**Comment by zerebubuth** [comment]
After #425, [Baker beach](http://www.openstreetmap.org/#map=16/37.7924/-122.4877) looks like this:

## Before
![baker-beach-z16-before](https://cloud.githubusercontent.com/assets/271360/11635194/fdc9f138-9d0c-11e5-9e11-d20e50018d56.jpg)

## After
![baker-beach-z16-after](https://cloud.githubusercontent.com/assets/271360/11635190/fa28fbbe-9d0c-11e5-878c-53b795b297e5.jpg)

With the following scene file snippet:

```yaml
    landuse:
        data: { source: osm }
        beach:
          filter: { kind: beach }
          draw:
            polygons:
              color: '#f2e780'
```
