### ISSUE TITLE
Missing water chunks near Vancouver BC

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#407]
http://tangrams.github.io/cinnabar-style-more-labels/#9/48.6828/-123.6401

![screen shot 2015-11-23 at 09 17 34](https://cloud.githubusercontent.com/assets/853051/11344183/973b70a2-91c4-11e5-9cf0-e69f62628522.png)

**Comment by nvkelso** [comment]
v0.5 tiles in prod.

**Comment by nvkelso** [comment]
Let's time box this for 4 hours to see if it's a minor problem. If it takes longer than that, let's move to v0.7.0 milestone.

**Comment by nvkelso** [comment]
Tip: try a different format for the same view.

**Comment by zerebubuth** [comment]
Looks like the issue here is a mixture of two things. First, the water polygon area cut-offs in the style are pretty huge. Here's the translation into "square pixels":

* Zoom 9: 106px^2
* Zoom 10: 342px^2
* Zoom 11: 342px^2
* Zoom 12: 342px^2
* Zoom 13: 273px^2
* Zoom 14: 21px^2

This makes a lot of sense when 1 (multi)polygon = 1 body of water, and the area is the total surface area of the (multi)polygon. In the case of the OSM oceans, we're using the [OpenStreetMapData split ocean polygons](http://openstreetmapdata.com/data/water-polygons) and so each split part has its own, smaller area which isn't big enough to trip the cut-off for inclusion above.

Since many of these occur at or near tile boundaries, merging isn't going to help. First, a work-around is to change the area cut-offs to 1px^2, as shown below.

```yaml
    water:
        data: { source: osm, layer: water }
        draw:
            polygons:
                order: 5
                #color: *water1
        lakes:
            filter:
                all:
                    - kind: [ocean, lake, water, riverbank, reservoir]
                any:
                    # limit show smaller landuse areas to higher zooms
                    - { $zoom: { min: 1 },  area: { min: 40000000000 } }
                    - { $zoom: { min: 2 },  area: { min: 20000000000 } }
                    # some weird natural earth scale set transition
                    - { $zoom: { min: 3 },  area: { min: 80000000000 } }
                    - { $zoom: { min: 4 },  area: { min: 5000000000 } }
                    - { $zoom: { min: 5 },  area: { min: 700000000 } }
                    - { $zoom: { min: 6 },  area: { min: 500000000 } }
                    - { $zoom: { min: 7 },  area: { min: 160000000 } }
                    - { $zoom: { min: 8 },  area: { min: 40000000 } }
                    - { $zoom: { min: 9 },  area: { min: 93481 } }
                    - { $zoom: { min: 10 }, area: { min: 23370 } }
                    - { $zoom: { min: 11 }, area: { min: 5842 } }
                    - { $zoom: { min: 12 }, area: { min: 1460 } }
                    - { $zoom: { min: 13 }, area: { min: 365 } }
                    - { $zoom: { min: 14 }, area: { min: 91 } }
                    - { $zoom: { min: 15 } }
            draw:
                polygons:
                    color: *water1
```

The proper fix might be to ignore the actual area of the individual polygons and just put [3.61e14](https://en.wikipedia.org/wiki/Ocean#Oceanic_divisions) as a constant area. Would putting such a large number make sense, or is it better to just leave the `area` property off and rely on the style to not filter the ocean polygons the same way it does the other water polygons? @nvkelso what do you think?
