### ISSUE TITLE
Fix up zoos & related tourism=attraction's (pois/landuse)

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#440]
`tourism:attraction` is used in **zoos** and other "tourist" recreation areas to tag points and polygons. It's often combined with `attraction=*` to provide more fidelity (that it's an animal & etc). Inside, zoos, the `zoo=*` tag is also used to indicate animal enclosures and `natural=*` to indicate if the landcover is grass, sand, etc. 

Whitelist **tourism** value for pois and landuse, and for POIs default to zoom 17 unless otherwise noted:

- [x] attraction
- [x] artwork
- [x] theme_park - **zoom 13** _likely candidate for variable zoom range_
- [x] wilderness_hut - **zoom 15**
- [x] hanami (flower viewing in Japan)
- [x] resort - **zoom 14** _likely candidate for variable zoom range_
- [x] trail_riding_station
- [x] aquarium - **zoom 14** _likely candidate for variable zoom range_
- [x] winery - **zoom 14** _likely candidate for variable zoom range_

Whitelist these **attraction** values for pois and landuse:

- [x] animal
- [x] water_slide
- [x] roller_coaster
- [x] summer_toboggan
- [x] carousel
- [x] amusement_ride
- [x] maze

We're not picking up landuse layer **natural** values of:

- [ ] sand
- [x] grass

We should whitelist the following landuse **zoo** tags:

- [x] enclosure
- [x] petting_zoo
- [x] aviary
- [x] wildlife_park

And we're missing **barrier** to wrap around the enclosures: 

- [x] fence (starting zoom 17)

Examples:
* Not-zoo point: https://www.openstreetmap.org/node/381538609
* Zoo map: https://www.openstreetmap.org/#map=18/37.73272/-122.50292
* Zoo polygon: https://www.openstreetmap.org/way/382818435

**Comment by zerebubuth** [comment]
The keys `attraction` and `zoo` are not included in our osm2pgsql style file, so we may be missing a few (most will probably have names, and so be included). Created #485 to track it, but we'll probably do okay without a reload for now.

**Comment by zerebubuth** [comment]
For each of these values, should their value be in the `kind` property? For example, [relation 5695997](http://www.openstreetmap.org/relation/5695997) has `attraction=animal`, `name=Asian Rhino`, `natural=sand`, `tourism=attraction` and `zoo=enclosure`.

What properties should this give on the final output polygon:

* `kind: attraction`, `attraction: animal`, `name: Asian Rhino`, `natural: sand` and `zoo: enclosure`?
* Or `kind: enclosure`, `attraction: animal`, `name: Asian Rhino`, `natural: sand` and `tourism: attraction`? 
* Or even `kind: animal` + ...?

**Comment by nvkelso** [comment]
This is similar to the extra `sport` attribute on pitches currently in tiles. Generally they are just `kind=pitch` for landuse polygons, and the label icon is driven by the `sport` value. 

So the question here is if `kind` should be set to `attraction` or `enclosure`. There are other attraction areas (like rides at amusement parks), so I vote of emphasizing the value of **zoo** in the enclosure case (where `zoo=*` has been defined). 

* `kind: enclosure`, `attraction: animal`, `name: Asian Rhino`, `natural: sand` and `tourism: attraction`

In the case of this [Hong Kong amusement park ride](https://www.openstreetmap.org/way/250708268),  a more specific key set beyond `tourism: attraction` hasn't been set, so I'd expect `kind: attraction`. 

But in the case of [this Disneyland ride](https://www.openstreetmap.org/way/129691054), there's been an `attraction: carousel` set in addition to `tourism: attraction` so I expect the `kind: carousel` to be set. Same for [this](https://www.openstreetmap.org/way/107280556) `kind: roller_coaster`.

**Comment by zerebubuth** [comment]
## King's Dominion Theme Park

### Carousel

![carousel-z17](https://cloud.githubusercontent.com/assets/271360/12403793/629a0ebc-be2e-11e5-9d8d-f3c7170dd78c.jpg)

### Roller Coaster

![intimidator-coaster-z17](https://cloud.githubusercontent.com/assets/271360/12403794/62ab5636-be2e-11e5-82cc-6288037c8e9c.jpg)

### Theme Park POI

![kings-dominion-z17](https://cloud.githubusercontent.com/assets/271360/12403795/62ad522e-be2e-11e5-8e8f-bca846c5daa6.jpg)

### Amusement Ride

![tornado-ride-z17](https://cloud.githubusercontent.com/assets/271360/12403801/62c4b090-be2e-11e5-99d4-88efed3e2b93.jpg)


## Shubencadie Wildlife Park

### Animal

![sable-island-horse-z17](https://cloud.githubusercontent.com/assets/271360/12403798/62b065c2-be2e-11e5-9522-6be25457eb19.jpg)

### Wildlife Park POI

![shubenacadie-wildlife-park-z17](https://cloud.githubusercontent.com/assets/271360/12403800/62c3a1be-be2e-11e5-9078-2ef8bff6c5fb.jpg)

## Aquarium

![aquarium-of-the-pacific-z18](https://cloud.githubusercontent.com/assets/271360/12403789/6295b43e-be2e-11e5-8865-be1999147caa.jpg)

## Artwork

![artwork-z19](https://cloud.githubusercontent.com/assets/271360/12403792/62978f2a-be2e-11e5-85bb-3c90887fc06c.jpg)

## Aviary

![budgie-buddies-z19](https://cloud.githubusercontent.com/assets/271360/12403790/62969f5c-be2e-11e5-87b3-b5c03fadc912.jpg)

## Resort

![disney-land-resort-z14](https://cloud.githubusercontent.com/assets/271360/12403791/62973656-be2e-11e5-8dbe-522e19cff53f.jpg)

## Water Slide

![fun-mountain-z17](https://cloud.githubusercontent.com/assets/271360/12403788/629571e0-be2e-11e5-9a15-483c10d7e1e0.jpg)

## Maize^W Maze

![lawyers-farm-corn-maze-z17](https://cloud.githubusercontent.com/assets/271360/12403796/62adcd4e-be2e-11e5-95c9-9128046e1586.jpg)

## Petting Zoo

![oaklawn-farm-zoo-z17](https://cloud.githubusercontent.com/assets/271360/12403797/62af8d78-be2e-11e5-8310-dd18927ecf36.jpg)

## Enclosure

![san-francisco-zoo-z17](https://cloud.githubusercontent.com/assets/271360/12403799/62b16fc6-be2e-11e5-9f73-2ea652271926.jpg)

## Trail Riding Station

(NOTE: couldn't find a polygonal one of these that wasn't also something else.)

![trail-riding-station-z19](https://cloud.githubusercontent.com/assets/271360/12403802/62c7061a-be2e-11e5-96b2-904d0a105f42.jpg)

## Wilderness Hut

![wendy-thompson-hut-z19](https://cloud.githubusercontent.com/assets/271360/12403803/62c7d13a-be2e-11e5-813f-8a7b49cf21fa.jpg)

## Winery

![winery-z19](https://cloud.githubusercontent.com/assets/271360/12403804/62c9a712-be2e-11e5-91fd-d0727120cc68.jpg)

## Hanami & Summer Toboggan

They're in the code changes, but I couldn't find examples of them to screenshot.

## Scene file

Scene file changes:

```yaml
textures:
    hilite:
      url: hilite.png

styles:
    hilite:
      base: polygons
      blend: overlay
      animated: false
      material:
        diffuse:
          texture: hilite
          mapping: planar
          scale: 0.1

layers:
    landusetest:
        data: { source: osm, layer: [landuse] }
        filter:
          kind:
            - attraction
            - artwork
            - theme_park
            - wilderness_hut
            - hanami
            - resort
            - trail_riding_station
            - aquarium
            - winery
            - animal
            - water_slide
            - roller_coaster
            - summer_toboggan
            - carousel
            - amusement_ride
            - maze
            - enclosure
            - petting_zoo
            - aviary
            - wildlife_park
        draw:
          hilite:
            color: '#000000ff'
            visible: true
            order: 30

    poistest:
      data: { source: osm, layer: [pois] }
      filter:
        kind: trail_riding_station
      draw:
        icons:
          sprite: stable
          visible: true
          interactive: true
```

Where `hilite.png` is a red and transparent chequerboard pattern.
