### ISSUE TITLE
Add aeroway gates to POIs layer

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#454]
See: https://wiki.openstreetmap.org/wiki/Tag:aeroway%3Dgate

They should probably get `kind=gate` but also `aeroway=gate` to differentiate them from other types of gates? There's some filtering in the stylesheet that generally excludes gates, though. So either requires coordinating or new kind value.

**Comment by nvkelso** [comment]
Starting zoom 16 (or z17 if that's too crowded).

**Comment by zerebubuth** [comment]
# SFO Boarding Area A & Domestic Terminal 1

Before:

![sfo-z17-before](https://cloud.githubusercontent.com/assets/271360/12115400/e15b2c48-b3a9-11e5-8b7e-07e9ea06f69a.jpg)

After:

![sfo-z17-after](https://cloud.githubusercontent.com/assets/271360/12115404/e567a76c-b3a9-11e5-9785-f75ff6d20a6a.jpg)

With scene file snippet:

```yaml
    aeroway-gate:
        data: { source: osm, layer: [pois] }
        filter: { kind: gate, aeroway: gate }
        draw:
            icons:
                visible: false
            text:
                visible: true
                interactive: true
                text_source: ref
                font:
                    fill: '#ff0000'
                    size: [[12,9px],[15,12px],[17,14px]]
```

@nvkelso what do you think? At the moment they come in at zoom 17, but could they come in earlier?
