### ISSUE TITLE
Add ref values for railway=station_entrances and aeroway=gate

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#527]
See also: 

* http://wiki.openstreetmap.org/wiki/Tag:railway%3Dsubway_entrance
* http://wiki.openstreetmap.org/wiki/Tag:aeroway%3Dgate

Based on feedback from Korea test here:

https://www.openstreetmap.org/edit?node=3824606390#map=19/37.50438/127.02449

We'd expose this in map display styles by concatenating the `ref` and `name` (like we do roads today). Once shields become a Tangram feature, we'd transition to a hybrid solution.

**Comment by nvkelso** [comment]
This looks to in prod, at least for subway entrances:

#19/48.86814/2.36145

![screen shot 2016-02-16 at 17 29 36](https://cloud.githubusercontent.com/assets/853051/13097067/00aba01a-d4d3-11e5-8316-bbae7ae91087.png)

**Comment by zerebubuth** [comment]
I'm not sure I understand - what do we have to add that's not already in the tiles?

From your screenshot, it looks like we've already got `ref` for `kind: subway_entrance`, and from the screenshot below you can see we've got `ref` for `kind: gate, aeroway: gate`:

![aeroway-gate](https://cloud.githubusercontent.com/assets/271360/13106707/9c3fdf08-d561-11e5-9fa6-ce9817e6843a.jpg)

The actual scene file snippet is:

```yaml
    aeroway-gate:
        data: { source: osm, layer: [pois] }
        filter: { kind: gate, aeroway: gate }
        draw:
            icons:
                visible: true
                interactive: true
            text:
                visible: true
                interactive: true
                text_source: ref
                font:
                    fill: '#ff0000'
                    size: [[12,9px],[15,12px],[17,14px]]
```

But I wasn't able to get the interactive bit to work.

From taginfo, it looks like there are 7 `railway=station_entrance` objects, and 131 `railway=train_station_entrance` objects. It's likely that we'd have better results looking for `entrance=*` on the outline of the station polygon, or building polygons within the station site relation (there are 991,072 `entrance=*` nodes, but it's not easy to tell how many are part of polygons). But that's a lot more work.
