### ISSUE TITLE
Add basic is_bicycle_route, bike lane left, right

### ISSUE THREAD

**Issue by nvkelso** [mapzen/vector-datasource#647]
Picking up thread in https://github.com/mapzen/vector-datasource/issues/391 to limit to simple change:

* Boolean for `is_bicycle_route` based on the relations (like `is_bus_route` logic)
* Indicate "best" network value for bicycle route (see https://github.com/mapzen/vector-datasource/issues/647#issuecomment-214572904 below)
* Indicate if bicycle lane left (way property)
* Indicate bicycle lane right (way property)
* Indicate bicycle contraflow (way property)

**Comment by nvkelso** [comment]
See line notes in https://github.com/mapzen/vector-datasource/pull/739 for indicating bicycle route network type (not just a boolean).

* https://github.com/mapzen/vector-datasource/pull/739#discussion_r61013189
* https://github.com/mapzen/vector-datasource/pull/739#discussion_r61013106
* https://github.com/mapzen/vector-datasource/pull/739#discussion_r61013242

**Comment by nvkelso** [comment]
We've added basic attributes (good), but we're missing a calculated `is_bicycle_route: yes`. Do we need that still? We include `bicycle_network` with values in `icn`, `ncn`, `rcn`, and `lcn` which is probably more useful. But sometimes a road might not part of a route relation and miss bicycle_network but still have a cycleway on it. Here's the logic from the scene file we're using for this for debug:

```
    bicycle-roads:
        data: { source: mapzen, layer: roads }
        filter: 
            any:
                - bicycle_network: true
                - cycleway: yes
                - cycleway_left: yes
                - cycleway_right: yes
                - cycleway_both: yes
```

**Comment by nvkelso** [comment]
More complete example:

```
    bicycle-roads:
        data: { source: mapzen, layer: roads }
        filter: 
            any:
                - bicycle_network: true
                - cycleway: true
                  not: { cycleway: no }
                - cycleway_left: true
                  not: { cycleway_left: no }
                - cycleway_right: true
                  not: { cycleway_right: no }
                - cycleway_both: true
                  not: { cycleway_both: no }
```
