### ISSUE TITLE
water features with boundary=yes gappy in some areas

### ISSUE THREAD

**Issue by meetar** [mapzen/vector-datasource#735]
Notably around Manhattan and some nearby areas:

<img width="657" alt="screen shot 2016-04-20 at 2 55 39 pm" src="https://cloud.githubusercontent.com/assets/459970/14686696/f992c2a6-0707-11e6-8fae-287380f3dba1.png">

Viewable here at time of writing: http://tangrams.github.io/explorer/#13.0/40.7609/-73.9744/boundary/yes

**Comment by zerebubuth** [comment]
Comment from Slack, for context:

> boundaries are gappy where there's two polygons with tangential sides. both subtract each other's boundaries.
>
> the previous approach (unioning all the water, then dividing the boundaries up) didn't have this problem but was far, far too slow. we should have a go and see if clipping the polygons to just a little bigger than a tile makes it manageable. otherwise, this might need some thinking (or NEAT tiles) to solve "properly".

**Comment by nvkelso** [comment]
Confirmed this is still a problem on dev with v1 tiles.

In the case of NYC area, we think this is because of the coastline derived water polygon (openstreetmapdata.com) is mostly coincidental with the riverbank polygons for Hudson, East River, and various riverbank channels of those rivers. Which is a widespread data problem we'll need to engineer around.

**Comment by nvkelso** [comment]
<img width="719" alt="screen shot 2016-09-21 at 11 23 36" src="https://cloud.githubusercontent.com/assets/853051/18723556/e95e72ae-7fed-11e6-9c00-e80cf0031889.png">

```
layers:
    water:
        data: { source: osm }
        draw:
            polygons:
                order: 2
                color: '#353535'
        boundary:
            filter: { boundary: true }
            draw:
                lines:
                    order: 3
                    color: red
                    width: 2px
```
